### ISSUE TITLE
Add custom config files for solr schema.

### ISSUE THREAD

**Issue by mcortes19** [chirripo/chirripo#36]
## Issue Type

 - Feature Idea
## Summary

In some cases, we need to add custom solr config schema in order to work with Drupal search api.

**Comment by kporras07** [comment]
Hi @mcortes19 

You can override solr config in the root of your project.

You need to create a docker-compose.override.yml with contents like this:

```
version: "3.6"

services:
  solr:
    volumes:
      - '../../../../solr/config:/config'
```

And then, you place your custom config in a solr/config folder in the root


Please give it a try and let me know if it works :)
